// src/pipeline/phases/delivery.js
// Phase 7: PR 생성

import chalk from "chalk";
import ora from "ora";
import { t } from "../../i18n/index.js";

export async function phasePR(ctx) {
  const projectTitle = ctx.state.project.title || "";
  const tasks = ctx.state.completedTasks;
  if (tasks.length === 0) return;

  const branchName = tasks[0].branchName;

  // 로컬 워크스페이스: PR 생성 전 push
  if (ctx.workspace?.isLocal) {
    try {
      ctx.workspace.gitPush(branchName);
      console.log(chalk.gray(`  ${t("pipeline.pushLog", { branch: branchName })}`));
    } catch (e) {
      console.log(chalk.yellow(`  ${t("pipeline.pushSkipped", { message: e.message })}`));
    }
  }

  const closesIssues = tasks
    .map((task) => `Closes #${task.issueNumber}`)
    .join("\n");
  const taskSummary = tasks
    .map(
      (task) =>
        `- **${task.title}** [${task.category || "feature"}] (${task.assignedAgent?.name} / ${task.assignedAgent?.modelKey})`
    )
    .join("\n");

  const communicationLog = ctx.state.exportMessageLog();

  const body = `${t("pipeline.prBody.changes")}
${t("pipeline.prBody.implementation", { title: projectTitle })}

${t("pipeline.prBody.relatedIssues")}
${closesIssues}

${t("pipeline.prBody.contents")}

${t("pipeline.prBody.taskList")}
${taskSummary}

${t("pipeline.prBody.reviewHistory")}
${tasks
  .map((task) => {
    const reviewIcon = task.reviewApproved ? t("pipeline.prBody.reviewApproved") : t("pipeline.prBody.reviewConditional");
    const qaIcon = task.qaPassed ? t("pipeline.prBody.qaPassed") : t("pipeline.prBody.qaConditional");
    const qaRetries = task.qaAttempts > 1 ? ` ${t("pipeline.prBody.qaRetries", { count: task.qaAttempts })}` : "";
    return `- **${task.title}**: ${reviewIcon} / QA ${qaIcon}${qaRetries}`;
  })
  .join("\n")}

${t("pipeline.prBody.meetingRecords")}
- ${t("pipeline.prBody.planningMeeting")}: #${ctx.state.github.planningIssue}

${t("pipeline.prBody.communicationLog")}
${communicationLog}

---
> ${t("pipeline.prBody.autoGenerated")}
>
> ${t("pipeline.prBody.modelAssignment")}
${ctx.team
  .getActiveAgents()
  .map((a) => `> - ${a.name} (${a.role}): \`${a.modelKey}\``)
  .join("\n")}`;

  const spinner = ora(t("pipeline.prSpinner", { category: projectTitle })).start();
  try {
    const pr = await ctx.github.createPR(
      `feat: ${projectTitle}`,
      body,
      branchName
    );
    spinner.succeed(t("pipeline.prCreated", { number: pr.number, url: ctx.github.prUrl(pr.number) }));

    for (const task of tasks) {
      if (task.projectItemId) {
        await ctx.github.setProjectItemStatus(task.projectItemId, "Done");
      }
    }
  } catch (e) {
    spinner.fail(t("pipeline.prSkipped", { category: projectTitle, message: e.message }));
  }
}
